# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_ip', models.GenericIPAddressField()),
                ('host_port', models.IntegerField()),
                ('room_number', models.IntegerField()),
                ('target_tmp', models.IntegerField()),
                ('speed_choice', models.CharField(max_length=20)),
            ],
        ),
    ]
