# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slave', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baseinfo',
            old_name='target_tmp',
            new_name='current_temp',
        ),
        migrations.RenameField(
            model_name='baseinfo',
            old_name='speed_choice',
            new_name='mode',
        ),
        migrations.AddField(
            model_name='baseinfo',
            name='speed',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='baseinfo',
            name='target_temp',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
