# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slave', '0002_auto_20160521_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseinfo',
            name='current_temp',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='baseinfo',
            name='target_temp',
            field=models.FloatField(),
        ),
    ]
