# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slave', '0003_auto_20160521_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseinfo',
            name='query_speed',
            field=models.CharField(default='standby', max_length=20),
            preserve_default=False,
        ),
    ]
