# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 10:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slave', '0004_baseinfo_query_speed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baseinfo',
            old_name='speed',
            new_name='current_speed',
        ),
    ]
