# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slave', '0005_auto_20160521_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseinfo',
            name='power_consump',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='baseinfo',
            name='power_price',
            field=models.FloatField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='baseinfo',
            name='total_cost',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
