# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slave', '0006_auto_20160605_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseinfo',
            name='is_log',
            field=models.CharField(default='false', max_length=20),
            preserve_default=False,
        ),
    ]
